### PR TITLE
Adding google style guide 😇

### PR DESCRIPTION
**Pull request by aelshamy**

### CODE REVIEW

**Comment by aelshamy** [comment]
Google just released a new style guide and I thought it might be helpful ;)

**Comment by ghobashy** [comment]
ya 3m ta3ala masr ba2a!! enta feen

**Comment by aelshamy** [comment]
a ya 3mona :) enta feen yaba ana kalmtek keteeer fash7' massenger w what's app w enta wala hena :)

**Comment by ghobashy** [comment]
mana telephony kan bayez, maknsh fe ay 7aga betfta7, bs it working now, i will call you el youmen dol

**Pull request merged**
